name: First_example

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4

            - name: welcome workflow
              run: |
                echo "hello world"
                ls -ltra
                cat Readme.md
                chmod +x hell.sh
                ./hell.sh
    second_job:
        needs: first_job
        runs-on: ubuntu-latest
        steps:
          - name: demo
            run: echo "second_job"
       
    third_job:
        needs: second_job
        runs-on: ubuntu-latest
        steps:
          - name: demo
            run: echo "third_job"
        
        
        